[build]
  publish = "frontend"
  command = ""

# Ensure JS files are served correctly
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

# Ensure CSS files are served correctly
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Service worker headers
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "application/javascript"