-- ===========================================
-- FARMING FAMILY SHOP - SAMPLE DATA
-- Backup Date: February 12, 2026
-- ===========================================
-- Insert 12 sample products
INSERT INTO products (
    name_bengali,
    name_english,
    category,
    unit_type,
    base_unit,
    available_units,
    selling_price,
    purchase_price,
    discount_allowed,
    current_quantity,
    current_weight,
    min_stock,
    avg_weight,
    is_active
  )
VALUES -- Eggs (3 products)
  (
    'সাদা ডিম',
    'White Egg',
    'ডিম',
    'piece',
    'pc',
    '[{"unit": "pc", "conversion": 1}, {"unit": "cage", "conversion": 30}, {"unit": "হালি", "conversion": 4}, {"unit": "ডজন", "conversion": 12}]'::jsonb,
    9.00,
    8.00,
    TRUE,
    500,
    0,
    100,
    NULL,
    TRUE
  ),
  (
    'লাল ডিম',
    'Red Egg',
    'ডিম',
    'piece',
    'pc',
    '[{"unit": "pc", "conversion": 1}, {"unit": "cage", "conversion": 30}, {"unit": "হালি", "conversion": 4}, {"unit": "ডজন", "conversion": 12}]'::jsonb,
    10.00,
    9.00,
    TRUE,
    300,
    0,
    50,
    NULL,
    TRUE
  ),
  (
    'কোয়েল ডিম',
    'Quail Egg',
    'ডিম',
    'piece',
    'pc',
    '[{"unit": "pc", "conversion": 1}, {"unit": "cage", "conversion": 42}]'::jsonb,
    3.00,
    2.50,
    TRUE,
    1000,
    0,
    200,
    NULL,
    TRUE
  ),
  -- Animal Food (2 products)
  (
    'মুরগির খাদ্য',
    'Chicken Feed',
    'প্রাণী খাদ্য',
    'weight',
    'pc',
    '[{"unit": "kg", "conversion": 1}]'::jsonb,
    45.00,
    40.00,
    TRUE,
    200,
    0,
    50,
    NULL,
    TRUE
  ),
  (
    'হাঁসের খাদ্য',
    'Duck Feed',
    'প্রাণী খাদ্য',
    'weight',
    'pc',
    '[{"unit": "kg", "conversion": 1}]'::jsonb,
    48.00,
    42.00,
    TRUE,
    150,
    0,
    30,
    NULL,
    TRUE
  ),
  -- Animal Medicine (2 products)
  (
    'ভিটামিন',
    'Vitamin',
    'প্রাণী ওষুধ',
    'piece',
    'pc',
    '[{"unit": "pc", "conversion": 1}, {"unit": "packet", "conversion": 10}]'::jsonb,
    120.00,
    100.00,
    TRUE,
    80,
    0,
    20,
    NULL,
    TRUE
  ),
  (
    'অ্যান্টিবায়োটিক',
    'Antibiotic',
    'প্রাণী ওষুধ',
    'piece',
    'pc',
    '[{"unit": "pc", "conversion": 1}]'::jsonb,
    250.00,
    200.00,
    TRUE,
    50,
    0,
    10,
    NULL,
    TRUE
  ),
  -- Farm Equipment (2 products)
  (
    'পানির পাত্র',
    'Water Feeder',
    'কৃষি যন্ত্রপাতি',
    'piece',
    'pc',
    '[{"unit": "pc", "conversion": 1}]'::jsonb,
    180.00,
    150.00,
    TRUE,
    40,
    0,
    10,
    NULL,
    TRUE
  ),
  (
    'খাবারের পাত্র',
    'Feed Tray',
    'কৃষি যন্ত্রপাতি',
    'piece',
    'pc',
    '[{"unit": "pc", "conversion": 1}]'::jsonb,
    220.00,
    180.00,
    TRUE,
    35,
    0,
    8,
    NULL,
    TRUE
  ),
  -- Livestock (3 products)
  (
    'ব্রয়লার মুরগি',
    'Broiler Chicken',
    'পাখি ও বাচ্চা',
    'both',
    'pc',
    '[{"unit": "pc", "conversion": 1}, {"unit": "kg", "conversion": 1}]'::jsonb,
    200.00,
    180.00,
    TRUE,
    50,
    75,
    20,
    1.5,
    TRUE
  ),
  (
    'সোনালি মুরগি',
    'Sonali Chicken',
    'পাখি ও বাচ্চা',
    'both',
    'pc',
    '[{"unit": "pc", "conversion": 1}, {"unit": "kg", "conversion": 1}]'::jsonb,
    280.00,
    250.00,
    TRUE,
    30,
    54,
    10,
    1.8,
    TRUE
  ),
  (
    'হাঁস',
    'Duck',
    'পাখি ও বাচ্চা',
    'both',
    'pc',
    '[{"unit": "pc", "conversion": 1}, {"unit": "kg", "conversion": 1}]'::jsonb,
    350.00,
    300.00,
    TRUE,
    25,
    50,
    8,
    2.0,
    TRUE
  );

-- Insert users
INSERT INTO users (
    username,
    full_name,
    role,
    can_add_products,
    can_edit_products,
    can_delete_products,
    can_add_sales,
    can_delete_sales,
    can_add_expenses,
    can_delete_expenses,
    can_view_reports,
    can_download_pdf,
    can_share_reports
  )
VALUES (
    'owner',
    'Owner',
    'owner',
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'mozzammel',
    'Mozzammel',
    'manager',
    TRUE,
    TRUE,
    false,
    TRUE,
    false,
    TRUE,
    false,
    TRUE,
    TRUE,
    TRUE
  ),
  (
    'cashier',
    'Cashier',
    'cashier',
    false,
    false,
    false,
    TRUE,
    false,
    false,
    false,
    false,
    false,
    false
  );

SELECT '✅ 02_insert_data.sql - Backup completed! 12 products, 3 users inserted.' AS message;